TE-1494 - Add Authorized Networks test, refactor auth ip and readonly tests
truenas/ScaleAutomation pull request #212
Opened 2024-04-08 18:28 UTC by jordan-mcgillivray005

2024-04-08 20:25 UTC, ericbsd requested changes

2024-04-08 20:25 UTC, ericbsd commented on test_cases/webui/shares/nfs/test_advanced_configurations.py
> +def setup_test(data_binding: list):
This should be in the class with an autouse fixture with function as scope. IT will be called automatically.

2024-04-09 11:33 UTC, markbainix commented on test_cases/webui/shares/nfs/test_advanced_configurations.py
> +def setup_test(data_binding: list):
if it is to be executed once (like the teardown) then scope = 'class'

2024-04-09 11:35 UTC, markbainix commented on test_cases/webui/shares/nfs/test_advanced_configurations.py
> +        NFS.set_network('192.168.1.52')
Do we want IP's in repo?

2024-04-09 13:12 UTC, jordan-mcgillivray005 commented on test_cases/webui/shares/nfs/test_advanced_configurations.py
> +        NFS.set_network('192.168.1.52')
I assumed this one was random. It is used in the manual test but I have changed it to be a confirmed random one.

2024-04-09 13:13 UTC, merged