TEN-1030 / 24/04.2 / Adding Read-Only Share Admin Directory Services test
truenas/ScaleAutomation pull request #324
Opened 2024-05-24 19:39 UTC by ericbsd

2024-05-28 16:04 UTC, markbainix commented on keywords/webui/directory_services.py
> +    def assert_directory_services_page_header(cls) -> bool:
is this needed? couldn't we just use `COM.assert_page_header('Directory Services')` in test case?

2024-05-28 16:18 UTC, markbainix commented on keywords/webui/directory_services.py
> +    def is_idmap_card_header_visible(cls) -> bool:
is it possible to use `COM.is_card_visible('title')` instead of creating methods?

2024-05-28 16:23 UTC, markbainix commented on test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_directory_services.py
> +    def tear_down_ad(self, ad_data):
tear_down probably should be one word "teardown_"

2024-05-28 16:32 UTC, markbainix approved these changes

2024-05-28 17:47 UTC, jordan-mcgillivray005 requested changes

2024-05-28 17:47 UTC, jordan-mcgillivray005 commented on keywords/webui/common_shares.py
> +    def click_do_not_start_or_do_not_restart(cls) -> None:
This method is going to add a lot of time if it's restart. Even 5 seconds per usage when used a lot is a long time. I think the original way of COM.click_button("do-not-start") or COM.click_button("do-not-restart") is better.

2024-05-28 18:08 UTC, ericbsd commented on test_cases/webui/restricted_admin/read-only-admin/test_read_only_admin_directory_services.py
> +    def test_read_only_admin_is_able_to_view_pre_configured_active_directory(self, ad_data, setup_ad, tear_down_ad):
They run fine in the same file.

2024-05-28 18:20 UTC, jordan-mcgillivray005 commented on keywords/webui/common_shares.py
> +    def click_do_not_start_or_do_not_restart(cls) -> None:
I updated the method NFS and SMB use for it in my last PR. COMSHARE.handle_share_service_dialog('nfs', 'start') or COMSHARE.handle_share_service_dialog('nfs', 'restart')

2024-05-29 11:02 UTC, ericbsd commented
![image](https://github.com/truenas/ScaleAutomation/assets/4249848/9a03c9d4-dabb-4050-ae42-356b0ecf1801)

2024-05-29 11:16 UTC, markbainix approved these changes

2024-05-29 11:39 UTC, jordan-mcgillivray005 approved these changes

2024-05-29 11:40 UTC, merged