TEN-1446 / 24.10 / Adding the test case to replace old DNS and static IP test case
truenas/ScaleAutomation pull request #425
Opened 2024-07-12 19:50 UTC by ericbsd

2024-07-12 20:17 UTC, ericbsd commented
![image](https://github.com/user-attachments/assets/d06fdb31-0a88-459b-ba72-ce8b931ccb9c)

2024-07-15 15:38 UTC, markbainix requested changes

2024-07-15 15:38 UTC, markbainix commented on keywords/webui/navigation.py
> +        This method navigates to the Shares page
This should be "Network page" not shares

2024-07-15 15:38 UTC, markbainix commented on keywords/webui/network.py
> +    def click_on_network_interface_edit_button(cls, interface_name: str) -> None:
suggest: name change - `click_edit_network_interface_button()` as this seems the format we have been using for several method names

2024-07-15 17:31 UTC, markbainix approved these changes

2024-07-15 17:31 UTC, merged