TEN-1455 / 24.10 / Adding 2 test cases to test system dataset in the UI
truenas/ScaleAutomation pull request #434
Opened 2024-07-17 19:21 UTC by ericbsd

2024-07-17 19:48 UTC, ericbsd commented
![image](https://github.com/user-attachments/assets/1a8aaf08-5e57-4711-80ca-2669ab2198d0)

2024-07-18 11:09 UTC, markbainix requested changes

2024-07-18 11:09 UTC, markbainix commented on test_cases/webui/system_settings/advanced/test_advenced_storage.py
> +        3. Verify the storage system dataset pool is changed on the UI and on the API.
numbering off.

2024-07-18 11:09 UTC, markbainix commented on test_cases/webui/system_settings/advanced/test_advenced_storage.py
> +        2. One the Storage card click configure.
is this supposed to be "On"?

2024-07-18 11:09 UTC, markbainix commented on test_cases/webui/system_settings/advanced/test_advenced_storage.py
> +        COM.is_dialog_visible('Warming')
should this be "assert"ed to ensure the dialog is present

2024-07-18 11:40 UTC, markbainix approved these changes

2024-07-18 12:38 UTC, markbainix approved these changes

2024-07-18 12:38 UTC, merged