TEN-1467 / 24.04.3 / Fixed test_verify_ssh_keys_downloaded instability
truenas/ScaleAutomation pull request #441
Opened 2024-07-22 19:15 UTC by ericbsd

2024-07-22 19:16 UTC, ericbsd commented
![Screenshot from 2024-07-22 16-13-34](https://github.com/user-attachments/assets/9ede1a4b-2a36-4ad7-b349-9861982c1549)

2024-07-23 11:44 UTC, markbainix requested changes

2024-07-23 11:44 UTC, markbainix commented on test_cases/webui/ssh/test_ssh_connections.py
> +        3. Click download actions button
renumber

2024-07-23 11:50 UTC, markbainix approved these changes

2024-07-23 11:50 UTC, merged